---
#   Copyright Red Hat, Inc. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.
#

- name: Setup RDO repository
  package:
    name: "centos-release-openstack-ocata"

# https://sensuapp.org/docs/latest/platforms/sensu-on-rhel-centos.html
- name: Setup Sensu repository
  copy:
    content: |
      [sensu]
      name=sensu
      baseurl=https://sensu.global.ssl.fastly.net/yum/$releasever/$basearch/
      gpgcheck=0
      enabled=1
    dest: /etc/yum.repos.d/sensu.repo

- name: Ensure yum-plugin-priorities is used
  package:
    name: "yum-plugin-priorities"
    state: "present"
  retries: "3"
  delay: "20"

- name: Install base packages
  package:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ monitoring_base_packages }}"
  retries: "3"
  delay: "20"

# https://github.com/sensu-plugins/sensu-plugins-memory-checks/issues/33
- name: Install vmstat gem
  gem:
    name: "vmstat"
    state: "present"
